name = "rueangrot-khanom"
compatibility_date = "2025-02-13"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "rueangrot-khanom-db"
database_id = "REPLACE_WITH_D1_ID"
migrations_dir = "./migrations"

[vars]
WHATSAPP_TO = "061 963 8979"
RESTAURANT_NAME = "Rueangrot Khanom"
RESTAURANT_TIMEZONE = "Asia/Bangkok"
